sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false


before_install:
  - npm i -g npm@5.5.0
before_script:
  - npm prune
after_success:
  - npm run semantic-release
