language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm i --save-dev standard-version
  - gem install chandler
  - echo Succeeded!
  - npm run releaseTh
  - git push --follow-tags origin master
  - chandler push

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
