language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm i --save-dev standard-version
  - gem install chandler
  - npm run tagging
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
